export interface Provider {
  id: string
  name: string
  defaultBaseUrl?: string
  apiKeyHint: string
  recommended: boolean
  type: "kodaai" | "openai" | "anthropic" | "gemini" | "openai-compat"
  docsUrl?: string
}

const RECOMMENDED_LABEL = "Recommended — your data never leaves KodaAI Cloud"
const EXTERNAL_WARN = "Not recommended unless you want to keep your data with a third party"

export const PROVIDERS: Provider[] = [
  {
    id: "kodaai",
    name: "KodaAI Cloud (Recommended)",
    apiKeyHint: "No API key needed (included with your plan)",
    recommended: true,
    type: "kodaai",
    docsUrl: "",
  },

  // ─── Major API providers ──────────────────────────────────────────
  {
    id: "openai",
    name: "OpenAI",
    defaultBaseUrl: "https://api.openai.com/v1",
    apiKeyHint: "sk-... from platform.openai.com",
    recommended: false,
    type: "openai",
    docsUrl: "https://platform.openai.com/api-keys",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    defaultBaseUrl: "https://api.anthropic.com/v1",
    apiKeyHint: "sk-ant-... from console.anthropic.com",
    recommended: false,
    type: "anthropic",
    docsUrl: "https://console.anthropic.com/settings/keys",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta",
    apiKeyHint: "AIza... from aistudio.google.com",
    recommended: false,
    type: "gemini",
    docsUrl: "https://aistudio.google.com/apikey",
  },
  {
    id: "mistral",
    name: "Mistral AI",
    defaultBaseUrl: "https://api.mistral.ai/v1",
    apiKeyHint: "API key from console.mistral.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://console.mistral.ai/api-keys",
  },
  {
    id: "cohere",
    name: "Cohere",
    defaultBaseUrl: "https://api.cohere.com/v1",
    apiKeyHint: "API key from dashboard.cohere.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://dashboard.cohere.com/api-keys",
  },
  {
    id: "ai21",
    name: "AI21 Labs",
    defaultBaseUrl: "https://api.ai21.com/studio/v1",
    apiKeyHint: "API key from ai21.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://www.ai21.com/account/api-key",
  },

  // ─── Router / aggregator providers ────────────────────────────────
  {
    id: "openrouter",
    name: "OpenRouter",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    apiKeyHint: "sk-or-... from openrouter.ai/keys",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://openrouter.ai/keys",
  },
  {
    id: "fastrouter",
    name: "FastRouter",
    defaultBaseUrl: "https://fastrouter.ai/api/v1",
    apiKeyHint: "API key from fastrouter.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://fastrouter.ai",
  },
  {
    id: "together",
    name: "Together AI",
    defaultBaseUrl: "https://api.together.xyz/v1",
    apiKeyHint: "API key from api.together.xyz",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://api.together.xyz/settings/api-keys",
  },

  // ─── Cloud provider AI services ───────────────────────────────────
  {
    id: "azure-openai",
    name: "Azure OpenAI",
    defaultBaseUrl: "https://YOUR_RESOURCE.openai.azure.com",
    apiKeyHint: "Azure API key + resource name",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://portal.azure.com",
  },
  {
    id: "aws-bedrock",
    name: "AWS Bedrock",
    defaultBaseUrl: "https://bedrock-runtime.YOUR_REGION.amazonaws.com",
    apiKeyHint: "AWS access key + secret key",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://aws.amazon.com/bedrock",
  },
  {
    id: "gcp-vertex",
    name: "GCP Vertex AI",
    defaultBaseUrl: "https://YOUR_PROJECT_ID.uc.r.appspot.com",
    apiKeyHint: "GCP service account JSON",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://console.cloud.google.com/vertex-ai",
  },
  {
    id: "ibm-watsonx",
    name: "IBM watsonx.ai",
    defaultBaseUrl: "https://us-south.ml.cloud.ibm.com",
    apiKeyHint: "IBM Cloud API key",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://cloud.ibm.com/watsonx",
  },
  {
    id: "oracle-oci",
    name: "Oracle OCI Generative AI",
    defaultBaseUrl: "https://generativeai.oci.YOUR_REGION.oraclecloud.com",
    apiKeyHint: "OCI API key",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://cloud.oracle.com/generative-ai",
  },

  // ─── Inference / GPU cloud providers ──────────────────────────────
  {
    id: "fireworks",
    name: "Fireworks AI",
    defaultBaseUrl: "https://api.fireworks.ai/inference/v1",
    apiKeyHint: "fw_... from fireworks.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://fireworks.ai/api-keys",
  },
  {
    id: "groq",
    name: "Groq",
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    apiKeyHint: "gsk_... from console.groq.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://console.groq.com/keys",
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    defaultBaseUrl: "https://api.perplexity.ai",
    apiKeyHint: "pplx-... from perplexity.ai/settings",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://www.perplexity.ai/settings/api",
  },
  {
    id: "replicate",
    name: "Replicate",
    defaultBaseUrl: "https://api.replicate.com/v1",
    apiKeyHint: "r8_... from replicate.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://replicate.com/account/api-tokens",
  },
  {
    id: "anyscale",
    name: "Anyscale",
    defaultBaseUrl: "https://api.endpoints.anyscale.com/v1",
    apiKeyHint: "esecret_... from anyscale.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://anyscale.com/endpoints",
  },
  {
    id: "sambanova",
    name: "SambaNova Cloud",
    defaultBaseUrl: "https://api.sambanova.ai/v1",
    apiKeyHint: "API key from cloud.sambanova.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://cloud.sambanova.ai/apis",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    defaultBaseUrl: "https://api.cerebras.ai/v1",
    apiKeyHint: "API key from cloud.cerebras.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://cloud.cerebras.ai",
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    defaultBaseUrl: "https://integrate.api.nvidia.com/v1",
    apiKeyHint: "nvapi-... from build.nvidia.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://build.nvidia.com",
  },
  {
    id: "octoai",
    name: "OctoAI",
    defaultBaseUrl: "https://text.octoai.run/v1",
    apiKeyHint: "API key from octoai.cloud",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://octoai.cloud",
  },
  {
    id: "banana",
    name: "Banana Dev",
    defaultBaseUrl: "https://api.banana.dev/v1",
    apiKeyHint: "API key from banana.dev",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://banana.dev",
  },
  {
    id: "baseten",
    name: "Baseten",
    defaultBaseUrl: "https://bridge.baseten.co/v1",
    apiKeyHint: "API key from baseten.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://baseten.ai",
  },
  {
    id: "modal",
    name: "Modal",
    defaultBaseUrl: "https://YOUR_WORKSPACE.modal.run",
    apiKeyHint: "API token from modal.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://modal.com",
  },
  {
    id: "friendliai",
    name: "FriendliAI",
    defaultBaseUrl: "https://api.friendli.ai/v1",
    apiKeyHint: "API key from friendli.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://friendli.ai",
  },
  {
    id: "abacus",
    name: "Abacus AI",
    defaultBaseUrl: "https://api.abacus.ai/v1",
    apiKeyHint: "API key from abacus.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://abacus.ai",
  },

  // ─── Specialized / inference startups ─────────────────────────────
  {
    id: "writer",
    name: "Writer",
    defaultBaseUrl: "https://api.writer.com/v1",
    apiKeyHint: "API key from writer.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://writer.com/api-keys",
  },
  {
    id: "aleph-alpha",
    name: "Aleph Alpha",
    defaultBaseUrl: "https://api.aleph-alpha.com/v1",
    apiKeyHint: "API key from aleph-alpha.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://www.aleph-alpha.com",
  },
  {
    id: "stability",
    name: "Stability AI",
    defaultBaseUrl: "https://api.stability.ai/v1",
    apiKeyHint: "API key from platform.stability.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://platform.stability.ai",
  },
  {
    id: "huggingface",
    name: "Hugging Face Inference",
    defaultBaseUrl: "https://api-inference.huggingface.co/v1",
    apiKeyHint: "hf_... from huggingface.co/settings/tokens",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://huggingface.co/settings/tokens",
  },
  {
    id: "forefront",
    name: "Forefront",
    defaultBaseUrl: "https://api.forefront.ai/v1",
    apiKeyHint: "API key from forefront.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://forefront.ai",
  },
  {
    id: "gooseai",
    name: "GooseAI",
    defaultBaseUrl: "https://api.goose.ai/v1",
    apiKeyHint: "API key from goose.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://goose.ai",
  },
  {
    id: "nlpcloud",
    name: "NLP Cloud",
    defaultBaseUrl: "https://api.nlpcloud.io/v1",
    apiKeyHint: "API key from nlpcloud.io",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://nlpcloud.io",
  },
  {
    id: "petals",
    name: "Petals",
    defaultBaseUrl: "http://localhost:PORT",
    apiKeyHint: "No API key (peer-to-peer)",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://petals.dev",
  },

  // ─── Local / self-hosted ──────────────────────────────────────────
  {
    id: "ollama",
    name: "Ollama (local)",
    defaultBaseUrl: "http://localhost:11434",
    apiKeyHint: "No API key needed (local)",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://ollama.com",
  },
  {
    id: "lm-studio",
    name: "LM Studio",
    defaultBaseUrl: "http://localhost:1234/v1",
    apiKeyHint: "No API key needed (local)",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://lmstudio.ai",
  },
  {
    id: "llamacpp",
    name: "llama.cpp",
    defaultBaseUrl: "http://localhost:8080/v1",
    apiKeyHint: "No API key needed (local)",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://github.com/ggerganov/llama.cpp",
  },
  {
    id: "tabbyapi",
    name: "TabbyAPI",
    defaultBaseUrl: "http://localhost:5000/v1",
    apiKeyHint: "No API key needed (local)",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://github.com/theroyallab/tabbyAPI",
  },
  {
    id: "koboldcpp",
    name: "KoboldCPP",
    defaultBaseUrl: "http://localhost:5001",
    apiKeyHint: "No API key needed (local)",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://github.com/LostRuins/koboldcpp",
  },
  {
    id: "text-generation",
    name: "Text Generation WebUI (oobabooga)",
    defaultBaseUrl: "http://localhost:5000",
    apiKeyHint: "No API key needed (local)",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://github.com/oobabooga/text-generation-webui",
  },
  {
    id: "vllm",
    name: "vLLM",
    defaultBaseUrl: "http://localhost:8000/v1",
    apiKeyHint: "No API key needed (local)",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://github.com/vllm-project/vllm",
  },
  {
    id: "localai",
    name: "LocalAI",
    defaultBaseUrl: "http://localhost:8080/v1",
    apiKeyHint: "No API key needed (local)",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://localai.io",
  },
  {
    id: "jan",
    name: "Jan",
    defaultBaseUrl: "http://localhost:1337/v1",
    apiKeyHint: "No API key needed (local)",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://jan.ai",
  },

  // ─── Additional inference providers ───────────────────────────────
  {
    id: "anyscale-endpoints",
    name: "Anyscale Endpoints",
    defaultBaseUrl: "https://api.endpoints.anyscale.com/v1",
    apiKeyHint: "API key from anyscale.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://anyscale.com",
  },
  {
    id: "modal-endpoints",
    name: "Modal Endpoints",
    defaultBaseUrl: "https://YOUR_APP.modal.run/v1",
    apiKeyHint: "API token from modal.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://modal.com",
  },
  {
    id: "deepinfra",
    name: "DeepInfra",
    defaultBaseUrl: "https://api.deepinfra.com/v1/openai",
    apiKeyHint: "API key from deepinfra.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://deepinfra.com",
  },
  {
    id: "lepton",
    name: "Lepton AI",
    defaultBaseUrl: "https://YOUR_WORKSPACE.lepton.run/v1",
    apiKeyHint: "API key from lepton.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://lepton.ai",
  },
  {
    id: "inferless",
    name: "Inferless",
    defaultBaseUrl: "https://api.inferless.com/v1",
    apiKeyHint: "API key from inferless.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://inferless.com",
  },
  {
    id: "beam",
    name: "Beam",
    defaultBaseUrl: "https://api.beam.cloud/v1",
    apiKeyHint: "API key from beam.cloud",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://beam.cloud",
  },
  {
    id: "runpod",
    name: "RunPod",
    defaultBaseUrl: "https://api.runpod.ai/v1",
    apiKeyHint: "API key from runpod.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://runpod.ai",
  },
  {
    id: "vastai",
    name: "Vast.ai",
    defaultBaseUrl: "https://api.vast.ai/v1",
    apiKeyHint: "API key from vast.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://vast.ai",
  },
  {
    id: "tensorbricks",
    name: "TensorBricks",
    defaultBaseUrl: "https://api.tensorbricks.com/v1",
    apiKeyHint: "API key from tensorbricks.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://tensorbricks.com",
  },
  {
    id: "nebius",
    name: "Nebius AI",
    defaultBaseUrl: "https://api.nebius.ai/v1",
    apiKeyHint: "API key from nebius.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://nebius.ai",
  },
  {
    id: "fPlat",
    name: "Featherless",
    defaultBaseUrl: "https://api.featherless.ai/v1",
    apiKeyHint: "API key from featherless.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://featherless.ai",
  },
  {
    id: "avataar",
    name: "Avataar",
    defaultBaseUrl: "https://api.avataar.ai/v1",
    apiKeyHint: "API key from avataar.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://avataar.ai",
  },
  {
    id: "mancer",
    name: "Mancer",
    defaultBaseUrl: "https://api.mancer.ai/v1",
    apiKeyHint: "API key from mancer.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://mancer.ai",
  },
  {
    id: "inferencecloud",
    name: "Inference Cloud",
    defaultBaseUrl: "https://api.inferencecloud.com/v1",
    apiKeyHint: "API key from inferencecloud.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://inferencecloud.com",
  },
  {
    id: "chutes",
    name: "Chutes",
    defaultBaseUrl: "https://api.chutes.ai/v1",
    apiKeyHint: "API key from chutes.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://chutes.ai",
  },
  {
    id: "recraft",
    name: "Recraft",
    defaultBaseUrl: "https://api.recraft.ai/v1",
    apiKeyHint: "API key from recraft.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://recraft.ai",
  },
  {
    id: "hyperbolic",
    name: "Hyperbolic",
    defaultBaseUrl: "https://api.hyperbolic.ai/v1",
    apiKeyHint: "API key from hyperbolic.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://hyperbolic.ai",
  },
  {
    id: "firn",
    name: "Firn",
    defaultBaseUrl: "https://api.firn.ai/v1",
    apiKeyHint: "API key from firn.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://firn.ai",
  },
  {
    id: "konkart",
    name: "Konkart AI",
    defaultBaseUrl: "https://api.konkart.ai/v1",
    apiKeyHint: "API key from konkart.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://konkart.ai",
  },
  {
    id: "gooey",
    name: "Gooey AI",
    defaultBaseUrl: "https://api.gooey.ai/v1",
    apiKeyHint: "API key from gooey.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://gooey.ai",
  },
  {
    id: "zyphra",
    name: "Zyphra",
    defaultBaseUrl: "https://api.zyphra.com/v1",
    apiKeyHint: "API key from zyphra.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://zyphra.com",
  },
  {
    id: "microsoft",
    name: "Microsoft Copilot",
    defaultBaseUrl: "https://api.copilot.microsoft.ai/v1",
    apiKeyHint: "Azure API key",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://copilot.microsoft.com",
  },
  {
    id: "meta",
    name: "Meta AI",
    defaultBaseUrl: "https://api.meta.ai/v1",
    apiKeyHint: "API key from meta.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://meta.ai",
  },
  {
    id: "xai",
    name: "xAI Grok",
    defaultBaseUrl: "https://api.x.ai/v1",
    apiKeyHint: "API key from x.ai",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://x.ai",
  },
  {
    id: "ai21-reframe",
    name: "AI21 Reframe",
    defaultBaseUrl: "https://api.ai21.com/studio/v1",
    apiKeyHint: "API key from ai21.com",
    recommended: false,
    type: "openai-compat",
    docsUrl: "https://ai21.com",
  },
  {
    id: "custom",
    name: "Custom OpenAI-compatible",
    defaultBaseUrl: "https://YOUR_ENDPOINT/v1",
    apiKeyHint: "Your API key (if required)",
    recommended: false,
    type: "openai-compat",
    docsUrl: "",
  },
]

export const PROVIDER_MAP = new Map(PROVIDERS.map((p) => [p.id, p]))

export function getProvider(id: string): Provider | undefined {
  return PROVIDER_MAP.get(id)
}

export const DEFAULT_PROVIDER = "kodaai"
